
spring:
  cloud:
    stream:
      bindings:
        orderProcessWithSideEffect-in-0:
          destination: raw-order-topic
        orderProcessWithSideEffect-out-0:
          destination: order-topic
        orderBranchingProcessor-in-0:
          destination: raw-order-topic
        orderBranchingProcessor-out-0:
          destination: order-topic
        orderBranchingProcessor-out-1:
          destination: errored-order
        upperCaseProcessor-in-0:
          destination: src-textMsg-topic
        upperCaseProcessor-out-0:
          destination: out-textMsg-topic-0
        upperCaseProcessor-out-1:
          destination: out-textMsg-topic-1
      kafka:
        streams:
          binder:
            brokers: localhost:29092
            functions:
              orderBranchingProcessor:
                applicationId: 'OrderBranchingProcessor'
              upperCaseProcessor:
                applicationId: 'lowerToUpperCaseStreamProcessor'
      function:
#        definition: orderProcessor;upperCaseProcessor;orderBranchingProcessor
        definition: orderBranchingProcessor;upperCaseProcessor;orderProcessWithSideEffect